name: Deploy Next.js App to VPS

on:
  push:
    branches:
      - main # Atau branch lain yang Anda gunakan untuk produksi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Sesuaikan dengan versi Node.js yang Anda gunakan
          cache: 'npm' # Atau 'yarn' jika Anda menggunakan Yarn

      - name: Install Dependencies
        run: npm install --force # Atau yarn install

      - name: Prepare .env file for production
        env:
          ENV_FILE_PRODUCTION: ${{ secrets.ENV_FILE_PRODUCTION }}
        run: |
          if [ -n "$ENV_FILE_PRODUCTION" ]; then
            echo "$ENV_FILE_PRODUCTION" > .env.production
          fi

      - name: Build Next.js App
        run: npm run build # Atau yarn build

      - name: Deploy to VPS via SSH (Initial Commands)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }} # Menggunakan password
          port: 22 # Port SSH default, sesuaikan jika berbeda
          script: |
            # Baris export PATH mungkin tidak lagi dibutuhkan di sini jika pm2 global
            # atau dipindahkan ke langkah final. Jika tidak ada perintah lain,
            # langkah ini bisa disederhanakan atau digabung.
            # export PATH=$PATH:/root/.local/share/pnpm # Pindahkan jika perlu untuk pm2 di langkah final
            cd ${{ secrets.VPS_TARGET_PATH }}
            echo "Deployment started at $(date)" >> deployment.log
            # Perintah pm2 stop dan delete tidak diperlukan lagi jika menggunakan startOrRestart
            # pm2 stop ekraf || true
            # pm2 delete ekraf || true
            # echo "PM2 process stopped/deleted." >> deployment.log
            echo "Initial setup on VPS. Files will be copied next." >> deployment.log

      - name: Copy files to VPS (Build artifacts)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }} # Menggunakan password
          port: 22
          source: ".next/,public/,package.json,package-lock.json,next.config.js,next.config.mjs,pm2.config.js,.env.production" # Sesuaikan daftar file/folder
          target: ${{ secrets.VPS_TARGET_PATH }}
          strip_components: 0 # Sesuaikan jika perlu

      - name: Execute remote commands on VPS (Final Steps)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }} # Menggunakan password
          port: 22
          script: |
            export PATH=$PATH:/root/.local/share/pnpm # Tambahkan ini jika pm2 ada di path ini dan dibutuhkan
            cd ${{ secrets.VPS_TARGET_PATH }}
            git pull origin main || true # Pastikan untuk menarik perubahan terbaru jika ada
            echo "Pulled latest changes from repository." >> deployment.log
            echo "Files copied. Running server-side commands at $(date)" >> deployment.log
            npm install --omit=dev --force # Atau yarn install --production
            echo "Dependencies installed on server." >> deployment.log
            npx prisma generate # Hanya jika menggunakan Prisma
            echo "Prisma client generated." >> deployment.log
            pm2 startOrRestart pm2.config.js --env production # Menggunakan startOrRestart
            echo "PM2 process restarted/started." >> deployment.log
            pm2 save
            echo "Deployment finished successfully at $(date)" >> deployment.log
            echo "--------------------------------------" >> deployment.log